openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
  description: API for managing tasks.

paths:
  /api/signup:
    post:
      summary: Create a new user account.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User created successfully.

  /api/login:
    post:
      summary: Authenticate a user and return a JWT.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '200':
          description: JWT token issued.

  /api/tasks:
    get:
      summary: Retrieve a list of tasks.
      responses:
        '200':
          description: List of tasks.

    post:
      summary: Create a new task.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Task created.

  /api/tasks/{taskId}:
    get:
      summary: Retrieve a specific task.
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task details.

    put:
      summary: Update a specific task.
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Task updated.

    delete:
      summary: Delete a specific task.
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Task deleted.

components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string

    Login:
      type: object
      properties:
        email:
          type: string
        password:
          type: string

    Task:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        status:
          enum: [pending, in-progress, completed]
          type: string
